server:
  port: 8085
spring:
  application:
    name: user-service
  h2:
    datasource:
      url: jdbc:h2:mem:userservice
      username: sa
      password: sa
      driverClassName: org.h2.Driver
    console:
      enabled: true
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.H2Dialect
